<?php

namespace Pn\PnBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BabysitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabysitterRepository extends EntityRepository
{

}
