<?php

namespace Pn\PnBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MoocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoocRepository extends EntityRepository
{
    public function getLatest($number = 4)
    {
        $qb = $this->createQueryBuilder('m')
            ->orderBy('m.created_at', 'DESC')
            ->setMaxResults($number);


        $query = $qb->getQuery();

        return $query->getResult();
    }
}
