<?php

namespace Pn\PnBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getLastBabysitters($number = 3)
    {
        $qb = $this->createQueryBuilder('b')
            ->where('b.type = \'nounou\'')
            ->orderBy('b.created_at', 'DESC')
            ->setMaxResults($number);


        $query = $qb->getQuery();

        return $query->getResult();
    }

    public function getBabysitterFromSearch($search, $max = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->where('b.address LIKE :search')
            ->setParameter('search', $search);
        if($max)
        {
            $qb->setMaxResults($max);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

    /**
     * List all the users except those who are in the array $arr
     *
     * @param $ids
     */
    public function findAllExcept($ids)
    {
        $qb = $this->createQueryBuilder('u');

        $query = $qb->select('u')
            ->where($qb->expr()->notIn('u.id', $ids))
            ->getQuery();


        return $query->getResult();
    }
}
