<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\NewsBundle\Entity;

use Sonata\ClassificationBundle\Model\CollectionInterface;
use Sonata\NewsBundle\Entity\BasePost as BasePost;
use Doctrine\ORM\Mapping as ORM;
use Sonata\NewsBundle\Model\PostInterface;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Post extends BasePost implements PostInterface
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $tags;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $comments;

    /**
     * @var \Application\Sonata\UserBundle\Entity\User
     */
    protected $author;

    /**
     * @var \Application\Sonata\MediaBundle\Entity\Media
     */
    protected $image;

    /**
     * @var \Application\Sonata\ClassificationBundle\Entity\Collection
     */
    protected $collection;








    /**
     * @ORM\PrePersist
     */
    public function setDefaultValues()
    {
        if (!$this->onHomePage) $this->onHomePage = false;
    }









    /**
     * Set author
     *
     * @param \Application\Sonata\UserBundle\Entity\User $author
     * @return Post
     */
    public function setAuthor($author = null)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Set image
     *
     * @param \Application\Sonata\MediaBundle\Entity\Media $image
     * @return Post
     */
    public function setImage($image = null)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Set collection
     *
     * @param \Application\Sonata\ClassificationBundle\Entity\Collection $collection
     * @return Post
     */
    public function setCollection(CollectionInterface $collection = null)
    {
        $this->collection = $collection;

        return $this;
    }


























    // GENERATED CODE

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var boolean
     */
    private $onHomePage;






    /**
     * Constructor
     */
    public function __construct()
    {
        $this->comments = new \Doctrine\Common\Collections\ArrayCollection();
        $this->tags = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set onHomePage
     *
     * @param boolean $onHomePage
     * @return Post
     */
    public function setOnHomePage($onHomePage)
    {
        $this->onHomePage = $onHomePage;

        return $this;
    }

    /**
     * Get onHomePage
     *
     * @return boolean
     */
    public function getOnHomePage()
    {
        return $this->onHomePage;
    }

    /**
     * Add comments
     *
     * @param \Application\Sonata\NewsBundle\Entity\Comment $comments
     * @return Post
     */
    public function addComment(\Application\Sonata\NewsBundle\Entity\Comment $comments)
    {
        $this->comments[] = $comments;

        return $this;
    }

    /**
     * Remove comments
     *
     * @param \Application\Sonata\NewsBundle\Entity\Comment $comments
     */
    public function removeComment(\Application\Sonata\NewsBundle\Entity\Comment $comments)
    {
        $this->comments->removeElement($comments);
    }

    /**
     * Get comments
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getComments()
    {
        return $this->comments;
    }



    /**
     * Get image
     *
     * @return \Application\Sonata\MediaBundle\Entity\Media
     */
    public function getImage()
    {
        return $this->image;
    }



    /**
     * Get author
     *
     * @return \Application\Sonata\UserBundle\Entity\User
     */
    public function getAuthor()
    {
        return $this->author;
    }



    /**
     * Get collection
     *
     * @return \Application\Sonata\ClassificationBundle\Entity\Collection
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Add tags
     *
     * @param \Application\Sonata\ClassificationBundle\Entity\Tag $tags
     * @return Post
     */
    public function addTag(\Application\Sonata\ClassificationBundle\Entity\Tag $tags)
    {
        $this->tags[] = $tags;

        return $this;
    }

    /**
     * Remove tags
     *
     * @param \Application\Sonata\ClassificationBundle\Entity\Tag $tags
     */
    public function removeTag(\Application\Sonata\ClassificationBundle\Entity\Tag $tags)
    {
        $this->tags->removeElement($tags);
    }

    /**
     * Get tags
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTags()
    {
        return $this->tags;
    }
}
