<?php

namespace Pn\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BabysittercategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabysittercategoryRepository extends EntityRepository
{
}
