<?php

namespace Pn\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentRepository extends EntityRepository
{
}
