<?php

namespace Pn\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildRepository extends EntityRepository
{
}
