<?php

namespace Application\Sonata\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Get Blog posts that are shown on home page
     *
     * @return array
     */
    public function getOnHomePageList()
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.onHomePage = true')
            ->orderBy('a.createdAt', 'DESC');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
